root_path: "/home/eugene/Desktop/machine-lerning-project/Drones-"
channels_file: "my_channels_list.txt"
api_id: ""
api_hash: ""
test: "my_test"
test_public_key: "my_test_key"
prod: "my_prod"
prod_public_key: "my_prod_key"
phone: ""
user: ""
